// import "./js/variables.js"
// import "./js/primitives.js"
// import "./js/toStrings.js"
// import "./js/toNumber.js"
// import "./js/toBoolean.js"
// import "./js/falsy-values.js"
// import "./js/module-6-methods.js"
// import "./js/module-6-pure-functions.js"
// import "./js/module-6-j.js"
// // import "./practice/modue-6-practice.js"
// import "./js/module-6-shorts.js"
// import "./js/module-8-propagation.js"
// import "./js/module-8-throttle.js"
// import "./js/module-8-debounce.js"
import "./js/module-8-IntersectionObserver.js"
// import "./js/references/refs.js"
import "./js/module-10-localStorage.js"
